<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RacesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('races')->insert([
            'name' => 'Aarakocra',
            'description' => 'Sequestered in high mountains atop tall trees, the aarakocra, sometimes called birdfolk, evoke fear and wonder.',
            'strength' => 0,
            'dexterity' => 2,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 1,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 23,
            'language_2' => 21, //Auran
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Aasimar (Protector)',
            'description' => 'Protector aasimar are charged by the powers of good to guard the weak, to strike at evil wherever it arises, and to stand vigilant against the darkness.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 1,
            'charisma' => 2,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 10,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Aasimar (Scourge)',
            'description' => 'Scourge aasimar are imbued with a divine energy that blazes intensely within them. It feeds a powerful desire to destroy evil.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 1,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 10,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Aasimar (Fallen)',
            'description' => 'An aasimar who was touched by dark powers as a youth or who turns to evil in early adulthood can become one of the fallen - a group of aasimar whose inner light has been replaced by shadow.',
            'strength' => 1,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 10,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Bugbear',
            'description' => 'Bugbears feature in the nightmare tales of many races — great, hairy beasts that creep through the shadows as quiet as cats.',
            'strength' => 2,
            'dexterity' => 1,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 6,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Centaur',
            'description' => 'The upper bodies of centaurs are comparable to human torsos in size, and their lower equine bodies average about 4 feet tall at the withers. They fill similar roles as cavalry warriors, messengers, outriders, and scouts.',
            'strength' => 2,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 1,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 3,
            'language_2' => 17,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Changeling',
            'description' => 'A changeling can shift its face and form with a thought as a form of artistic and emotional expression.',
            'strength' => 0,
            'dexterity' => 1,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 2,
            'language_1' => null,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Dragonborn',
            'description' => 'Dragonborn look very much like dragons standing erect in humanoid form, though they lack wings or a tail.',
            'strength' => 2,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 1,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 11,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Hill Dwarf',
            'description' => 'Bold and hardy, dwarves are known as skilled warriors, miners, and workers of stone and metal.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 2,
            'intelligence' => 0,
            'wisdom' => 1,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 2,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Mountain Dwarf',
            'description' => 'Bold and hardy, dwarves are known as skilled warriors, miners, and workers of stone and metal.',
            'strength' => 2,
            'dexterity' => 0,
            'constitution' => 2,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 2,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Gray Dwarf (Duergar)',
            'description' => 'Bold and hardy, dwarves are known as skilled warriors, miners, and workers of stone and metal.',
            'strength' => 1,
            'dexterity' => 0,
            'constitution' => 2,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 2,
            'language_2' => 22,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'High Elf',
            'description' => 'Elves are a magical people of otherworldly grace, living in the world but not entirely part of it.',
            'strength' => 0,
            'dexterity' => 2,
            'constitution' => 0,
            'intelligence' => 1,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 1,
            'language_1' => 3,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Wood Elf',
            'description' => 'Elves are a magical people of otherworldly grace, living in the world but not entirely part of it.',
            'strength' => 0,
            'dexterity' => 2,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 1,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 35,
            'languages' => 0,
            'language_1' => 3,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Dark Elf (Drow)',
            'description' => 'Elves are a magical people of otherworldly grace, living in the world but not entirely part of it.',
            'strength' => 0,
            'dexterity' => 2,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 1,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 3,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Eladrin (Elf)',
            'description' => 'Elves are a magical people of otherworldly grace, living in the world but not entirely part of it.',
            'strength' => 0,
            'dexterity' => 2,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 1,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 3,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Sea Elf',
            'description' => 'Elves are a magical people of otherworldly grace, living in the world but not entirely part of it.',
            'strength' => 0,
            'dexterity' => 2,
            'constitution' => 1,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 3,
            'language_2' => 21,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Shadar Kai (Elf)',
            'description' => 'Elves are a magical people of otherworldly grace, living in the world but not entirely part of it.',
            'strength' => 0,
            'dexterity' => 2,
            'constitution' => 1,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 3,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Firbolg',
            'description' => 'Firbolg tribes cloister in remote forest strongholds, preferring to spend their days in quiet harmony with the woods.',
            'strength' => 1,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 2,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 3,
            'language_2' => 4,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Air Genasi',
            'description' => 'Genasi carry the power of the elemental planes of air, earth, fire, and water in their blood.</p><p>As an air genasi, you are descended from the djinn. As changeable as the weather, your moods shift from calm to wild and violent with little warning, but these storms rarely last long.',
            'strength' => 0,
            'dexterity' => 1,
            'constitution' => 2,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => null,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Earth Genasi',
            'description' => 'Genasi carry the power of the elemental planes of air, earth, fire, and water in their blood.</p><p>As an earth genasi, you have inherited some measure of control over earth, reveling in superior strength and solid power.',
            'strength' => 1,
            'dexterity' => 0,
            'constitution' => 2,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => null,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Fire Genasi',
            'description' => 'Genasi carry the power of the elemental planes of air, earth, fire, and water in their blood.</p><p>As a fire genasi, you have inherited the volatile mood and keen mind of the efreet.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 2,
            'intelligence' => 1,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => null,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Water Genasi',
            'description' => 'Genasi carry the power of the elemental planes of air, earth, fire, and water in their blood.</p><p>The lapping of waves, the spray of sea foam on the wind, the ocean depths—all of these things call to your heart.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 2,
            'intelligence' => 0,
            'wisdom' => 1,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => null,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Githyanki',
            'description' => 'Long ago, the gith rose up to overthrow the mind flayers that held them in servitude, but two factions arose that remain bitter enemies today.',
            'strength' => 2,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 1,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 1,
            'language_1' => 25,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Githzerai',
            'description' => 'Long ago, the gith rose up to overthrow the mind flayers that held them in servitude, but two factions arose that remain bitter enemies today.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 1,
            'wisdom' => 2,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 25,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Forest Gnome',
            'description' => 'A gnome’s energy and enthusiasm for living shines through every inch of his or her tiny body.',
            'strength' => 0,
            'dexterity' => 1,
            'constitution' => 0,
            'intelligence' => 2,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 5,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Rock Gnome',
            'description' => 'A gnome’s energy and enthusiasm for living shines through every inch of his or her tiny body.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 1,
            'intelligence' => 2,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 5,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Deep Gnome',
            'description' => 'A gnome’s energy and enthusiasm for living shines through every inch of his or her tiny body.',
            'strength' => 0,
            'dexterity' => 1,
            'constitution' => 0,
            'intelligence' => 2,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 5,
            'language_2' => 22,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Goblin',
            'description' => 'Goblins occupy an uneasy place in a dangerous world, and they react by lashing out at any creatures they believe they can bully.',
            'strength' => 0,
            'dexterity' => 2,
            'constitution' => 1,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 6,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Goliath',
            'description' => 'Strong and reclusive, every day brings a new challenge to a goliath.',
            'strength' => 2,
            'dexterity' => 0,
            'constitution' => 1,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 4,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Half-Elf',
            'description' => 'Half-elves combine what some say are the best qualities of their elf and human parents.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 2,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 3,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Half-Elf (Wood)',
            'description' => 'Half-elves combine what some say are the best qualities of their elf and human parents.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 2,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 3,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Half-Elf (Moon/Sun)',
            'description' => 'Half-elves combine what some say are the best qualities of their elf and human parents.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 2,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 3,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Half-Elf (Drow)',
            'description' => 'Half-elves combine what some say are the best qualities of their elf and human parents.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 2,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 3,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Half-Elf (Aquatic)',
            'description' => 'Half-elves combine what some say are the best qualities of their elf and human parents.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 2,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 3,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Lightfoot Halfling',
            'description' => 'The diminutive halflings survive in a world full of larger creatures by avoiding notice or, barring that, avoiding offense.',
            'strength' => 0,
            'dexterity' => 2,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 1,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 7,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Stout Halfling',
            'description' => 'The diminutive halflings survive in a world full of larger creatures by avoiding notice or, barring that, avoiding offense.',
            'strength' => 0,
            'dexterity' => 2,
            'constitution' => 1,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 7,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Ghostwise Halfling',
            'description' => 'The diminutive halflings survive in a world full of larger creatures by avoiding notice or, barring that, avoiding offense.',
            'strength' => 0,
            'dexterity' => 2,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 1,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 7,
            'language_2' => 29,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Half-Orc',
            'description' => 'Half-orcs’ grayish pigmentation, sloping foreheads, jutting jaws, prominent teeth, and towering builds make their orcish heritage plain for all to see.',
            'strength' => 2,
            'dexterity' => 0,
            'constitution' => 1,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 8,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Hobgoblin',
            'description' => 'War is the lifeblood of hobgoblins. Its glories are the dreams that inspire them. Its horrors don’t feature in their nightmares.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 2,
            'intelligence' => 1,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 6,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Human',
            'description' => 'Humans are the most adaptable and ambitious people among the common races. Whatever drives them, humans are the innovators, the achievers, and the pioneers of the worlds.',
            'strength' => 1,
            'dexterity' => 1,
            'constitution' => 1,
            'intelligence' => 1,
            'wisdom' => 1,
            'charisma' => 1,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 1,
            'language_1' => null,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Kalashtar',
            'description' => 'The kalashtar are a compound race created from the union of humanity and renegade spirits from the plane of dreams.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 1,
            'charisma' => 1,
            'bonus' => 1,
            'speed' => 30,
            'languages' => 1,
            'language_1' => 28,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Kenku',
            'description' => 'Haunted by an ancient crime that robbed them of their wings, the kenku wander the world as vagabonds and burglars who live at the edge of human society.',
            'strength' => 0,
            'dexterity' => 2,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 1,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 21,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Kobold',
            'description' => 'Kobolds are typically timid and shy away from conflict, but they are dangerous and vicious if cornered.',
            'strength' => -2,
            'dexterity' => 2,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 11,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Lizardfolk',
            'description' => 'Lizardfolk possess an alien and inscrutable mindset, their desires and thoughts driven by a different set of basic principles than those of warm-blooded creatures.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 2,
            'intelligence' => 0,
            'wisdom' => 1,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 11,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Loxodon',
            'description' => 'Humanoid elephants, loxodons are strong, calm, and wise.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 2,
            'intelligence' => 0,
            'wisdom' => 1,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 13,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Minotaur',
            'description' => 'The minotaurs of Ravnica are strong in body, dedication, and courage. They are at home on the battlefield, willing to fight for their various causes.',
            'strength' => 2,
            'dexterity' => 0,
            'constitution' => 1,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 15,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Orc',
            'description' => 'Orcs live a life that has no place for weakness, and every warrior must be strong enough to take what is needed by force.',
            'strength' => 2,
            'dexterity' => 0,
            'constitution' => 1,
            'intelligence' => -2,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 8,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Beasthide Shifter',
            'description' => 'Shifters - sometimes called the weretouched - are humanoids with a bestial aspect.',
            'strength' => 0,
            'dexterity' => 1,
            'constitution' => 2,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => null,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Longtooth Shifter',
            'description' => 'Shifters - sometimes called the weretouched - are humanoids with a bestial aspect.',
            'strength' => 2,
            'dexterity' => 1,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => null,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Swiftstride Shifter',
            'description' => 'Shifters - sometimes called the weretouched - are humanoids with a bestial aspect.',
            'strength' => 0,
            'dexterity' => 2,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 1,
            'bonus' => 0,
            'speed' => 35,
            'languages' => 0,
            'language_1' => null,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Wildhunt Shifter',
            'description' => 'Shifters - sometimes called the weretouched - are humanoids with a bestial aspect.',
            'strength' => 0,
            'dexterity' => 1,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 2,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => null,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Simic Hybrid',
            'description' => 'The Simic Combine uses magic to transfer the traits of animals into humans, elves, and vedalken.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 2,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 1,
            // bonus cannot be applied to constitution.
            'speed' => 30,
            'languages' => 0,
            // Has the option to choose between Elvish or Vedalken.
            'language_1' => null,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Tabaxi',
            'description' => 'Hailing from a strange and distant land, wandering tabaxi are catlike humanoids driven by curiosity to collect interesting artifacts, gather tales and stories, and lay eyes on all the world’s wonders.',
            'strength' => 0,
            'dexterity' => 2,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 1,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => null,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Tiefling',
            'description' => 'To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye: this is the lot of the tiefling.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 1,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 20,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Feral Tiefling',
            'description' => 'To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye: this is the lot of the tiefling.',
            'strength' => 0,
            'dexterity' => 2,
            'constitution' => 0,
            'intelligence' => 1,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 20,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Tiefling (Asmodeus)',
            'description' => 'To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye: this is the lot of the tiefling.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 1,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 20,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Tiefling (Baalzebul)',
            'description' => 'To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye: this is the lot of the tiefling.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 1,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 20,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Tiefling (Dispater)',
            'description' => 'To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye: this is the lot of the tiefling.',
            'strength' => 0,
            'dexterity' => 1,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 20,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Tiefling (Fierna)',
            'description' => 'To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye: this is the lot of the tiefling.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 1,
            'charisma' => 2,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 20,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Tiefling (Glasya)',
            'description' => 'To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye: this is the lot of the tiefling.',
            'strength' => 0,
            'dexterity' => 1,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 20,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Tiefling (Levistus)',
            'description' => 'To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye: this is the lot of the tiefling.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 1,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 20,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Tiefling (Mammon)',
            'description' => 'To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye: this is the lot of the tiefling.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 1,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 20,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Tiefling (Mephistopheles)',
            'description' => 'To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye: this is the lot of the tiefling.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 1,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 20,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Tiefling (Zariel)',
            'description' => 'To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye: this is the lot of the tiefling.',
            'strength' => 1,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 20,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Tortle',
            'description' => 'What many tortles consider a simple life, others might call a life of adventure. They are nomad survivalists eager to explore the wilderness.',
            'strength' => 2,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 0,
            'wisdom' => 1,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 21,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Triton',
            'description' => 'Long-established guardians of the deep ocean floor, in recent years the noble tritons have become increasingly active in the world above.',
            'strength' => 1,
            'dexterity' => 0,
            'constitution' => 1,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 1,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 21,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Vedalkan',
            'description' => 'The blue-skinned vedalken strive for perfection above all else.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 2,
            'wisdom' => 1,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 1,
            'language_1' => 18,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Verdan',
            'description' => 'The verdan owe their existence to chaos - doing their best to find their way in an unfamiliar world...',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 1,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 6,
            // Can also speak with Telepathy
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Warforged Envoy',
            'description' => 'Warforged are formed from a blend of organic and inorganic materials. Built as weapons, they must now find a purpose beyond the war.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 1,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            // Bonus must be applied to two different skills
            'bonus' => 2,
            'speed' => 30,
            'languages' => 1,
            'language_1' => null,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Warforged Juggernaut',
            'description' => 'Warforged are formed from a blend of organic and inorganic materials. Built as weapons, they must now find a purpose beyond the war.',
            'strength' => 2,
            'dexterity' => 0,
            'constitution' => 1,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => null,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Warforged Skirmisher',
            'description' => 'Warforged are formed from a blend of organic and inorganic materials. Built as weapons, they must now find a purpose beyond the war.',
            'strength' => 0,
            'dexterity' => 2,
            'constitution' => 1,
            'intelligence' => 0,
            'wisdom' => 0,
            'charisma' => 0,
            'bonus' => 0,
            'speed' => 35,
            'languages' => 0,
            'language_1' => null,
            'language_2' => null,
            'language_3' => null,
        ]);
        DB::table('races')->insert([
            'name' => 'Yuan-ti Pureblood',
            'description' => 'The serpent creatures known as yuan-ti are all that remains of an ancient, decadent human empire.',
            'strength' => 0,
            'dexterity' => 0,
            'constitution' => 0,
            'intelligence' => 1,
            'wisdom' => 0,
            'charisma' => 2,
            'bonus' => 0,
            'speed' => 30,
            'languages' => 0,
            'language_1' => 9,
            'language_2' => 11,
            'language_3' => null,
        ]);
    }

}
